**Семинар 1**

In [1]:
from sem_3 import *

In [ ]:
xi_p, xi1_p, a = simulate_collisions(check_conservation=True, save_to_file=False)

Проверки сохранения:
Относительная скорость: 3.55e-15
Энергия: 4.26e-14
Импульс: 1.78e-15


In [3]:
xi_p

array([[-1.50456931,  1.87352468,  2.66043536],
       [-1.58402165, -0.4503979 , -3.74931301],
       [ 0.36769494,  1.11466963, -0.14292179],
       ...,
       [ 2.07515755, -7.54746063, -0.85005607],
       [-4.98044572,  3.47528485,  0.25711365],
       [ 0.30611208,  0.18115184,  3.37688016]])

**Семинар 2**

In [6]:
N = 20
xi_cut = 4.8

(xi_x, xi_y, xi_z), dxi = create_velocity_grid(N, N, N, xi_cut)

In [8]:
a_snapped, snapped_idx = snap_collision_velocities(a, (xi_x, xi_y, xi_z), dxi)

In [9]:
a_snapped_filtered, snapped_idx_filtered = filter_collision_nodes(a_snapped, snapped_idx, xi_cut)
print(np.shape(a_snapped_filtered))
print("Первая проверка по размеру пройдена")

(8, 5616)
Первая проверка по размеру пройдена


In [10]:
a_updated = compute_post_collision_velocities_sem_2(a_snapped_filtered, 1.0)

In [11]:
lam1, lam2, mu1, mu2, r = find_interpolating_nodes_and_weights(a_updated, (xi_x, xi_y, xi_z), dxi, xi_cut)

In [12]:
print(np.shape(lam1))
print("Вторая проверка по размеру пройдена")

(3, 3390)
Вторая проверка по размеру пройдена


In [13]:
print("проверка r:")
np.all((r >= 0) & (r <= 1))

проверка r:


True

In [142]:
print("Проверка закона сохранения импульса")
print("lam1 + mu1:")
print(lam1 + mu1)
print("lam2 + mu2:")
print(lam2 + mu2)
print("Видно, что все координаты либо совпадают, либо отличаются на +-1")

Проверка закона сохранения импульса
lam1 + mu1:
[[16  8 25 ... 26 14 19]
 [23 11 21 ... 11 22 19]
 [12 12 14 ... 20 19 14]]
lam2 + mu2:
[[16  7 26 ... 25 15 18]
 [23 10 22 ... 10 23 18]
 [12 11 15 ... 19 20 13]]
Видно, что все координаты либо совпадают, либо отличаются на +-1


**Семинар 3**

In [143]:
import sem_3
import importlib
importlib.reload(sem_3)

<module 'sem_3' from '/Users/ivankasyanov/Desktop/Физтех/3 курс/ВычМаты/проект/Без названия/compmathproject/code/sem_3.py'>

In [ ]:
N = 20
xi_cut = 4.8
tau = 0.02
T_tilde = 0.95
time_steps = int(0.4 / tau)
# f_max = 1 / ((2 * pi) ** 1.5)
# V_sph = 4 * pi * xi_cut ** 3 / 3
N_0 = 4224
W_min = (N_0 * xi_cut ** 4) / (6 * sqrt(pi))
N_v = int(W_min * tau)
f, xi_grid, dxi = initialize_distribution(N, xi_cut, T_tilde, condition=1)
print("initialize_distribution done")
n, u, T = compute_macro_parameters(f, xi_grid, dxi)
print("compute_macro_parameters done")
u_star, T_star = newton_method(xi_grid, dxi, u, T)
print("newton_method done")
f_M = np.exp(-0.5 * (xi_grid - u_star) ** 2 / T_star)
volume = dxi[0] * dxi[1] * dxi[2]
f_M /= np.sum(f_M, axis = 0) * volume
# print(np.sum((f - f_M) ** 2))
initial_norms = compute_norms(f, f_M, xi_grid, dxi, xi_cut)
print("compute_norms done")
delta_k = []
for t in range(time_steps):
    # Добавляем номер шага в вывод
    print(f"\n--- Step {t+1}/{time_steps} ---")
    
    # Вычисление интеграла столкновений
    f = compute_collision_integral(f, xi_grid, dxi, xi_cut, N_v, tau=tau)
    print(f"Step {t+1}: compute_collision_integral done")
    
    # Вычисление норм
    norms = compute_norms(f, f_M, xi_grid, dxi, xi_cut)
    print(f"Step {t+1}: compute_norms done")
    
    # Сохранение результатов
    delta_k.append([norm / init_norm for norm, init_norm in zip(norms, initial_norms)])

initialize_distribution done
compute_macro_parameters done
newton_method done
compute_norms done

--- Step 1/20 ---
Step 1: compute_collision_integral done
Step 1: compute_norms done

--- Step 2/20 ---


/var/folders/qq/pjggzry53mq7xbvhcjr59g800000gp/T/ipykernel_86039/639031758.py:37: RuntimeWarning: invalid value encountered in divide
  delta_k.append([norm / init_norm for norm, init_norm in zip(norms, initial_norms)])


Step 2: compute_collision_integral done
Step 2: compute_norms done

--- Step 3/20 ---
Step 3: compute_collision_integral done
Step 3: compute_norms done

--- Step 4/20 ---
Step 4: compute_collision_integral done
Step 4: compute_norms done

--- Step 5/20 ---
Step 5: compute_collision_integral done
Step 5: compute_norms done

--- Step 6/20 ---
Step 6: compute_collision_integral done
Step 6: compute_norms done

--- Step 7/20 ---
Step 7: compute_collision_integral done
Step 7: compute_norms done

--- Step 8/20 ---
Step 8: compute_collision_integral done
Step 8: compute_norms done

--- Step 9/20 ---
Step 9: compute_collision_integral done
Step 9: compute_norms done

--- Step 10/20 ---
Step 10: compute_collision_integral done
Step 10: compute_norms done

--- Step 11/20 ---
Step 11: compute_collision_integral done
Step 11: compute_norms done

--- Step 12/20 ---
Step 12: compute_collision_integral done
Step 12: compute_norms done

--- Step 13/20 ---
Step 13: compute_collision_integral done
Ste

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

Проверка №1. Консервативность интеграла.

Проверка №2. Симметрия интеграла. <mark>(Исправленная, проверить работает ли)</mark>

~~Проверка №3. Сходимость интеграла по шагу скоростной сетки.~~

In [ ]:
# Conservation check
n_new, u_new, T_new = compute_macro_parameters(f, xi_grid, dxi)
print(f"Conservation check: Δn={abs(n_new - n)}, Δu={np.linalg.norm(u_new - u)}, ΔT={abs(T_new - T)}")

# Symmetry check
f_0 = f.copy()
tau_sym = 1e-6
time_steps_sym = int(100 * tau_sym / tau)
for _ in range(time_steps_sym):
    f = compute_collision_integral(f, xi_grid, dxi, xi_cut, N_v, tau=tau_sym)
I = (f - f_0) / (100 * tau_sym)

# Проверяем форму массива I для диагностики
print("Shape of I:", I.shape)  # Должно быть (N, N) для 2D

# Вычисляем симметричную ошибку для 2D массива
sym_error = np.sqrt(np.sum((I[:N//2, :] - I[N-1:N//2-1:-1, :])**2)) / np.sqrt(0.5 * np.sum(I**2))
print(f"Symmetry error: {sym_error}")

# Convergence and other checks would require additional runs with different N and p
# Plotting delta_k vs model solution

t = np.array([i * tau for i in range(time_steps)])
model = -t * (16 / (5 * sqrt(2 * pi))) * sqrt(T)

# Repeat for t=2 and condition=2 as needed

Сохранение и загрузка посчитанных данных

In [175]:
import os
import numpy as np
import json

# Создаём папку для данных, если ее нет
os.makedirs('data', exist_ok=True)

# Сохраняем все данные
def save_all_data():
    data_to_save = {
        # Основные массивы
        'delta_k': delta_k,
        'f_M': f_M,
        'xi_grid': xi_grid,
        'dxi': dxi,

        # Макропараметры
        'n': n,
        'u': u,
        'T': T,
        'u_star': u_star,
        'T_star': T_star,

        # Нормы и модель
        'initial_norms': initial_norms,

        # Параметры симуляции
        'params': {
            'N': N,
            'xi_cut': xi_cut,
            'tau': tau,
            'T_tilde': T_tilde,
            'time_steps': time_steps,
            'N_0': N_0,
            'N_v': N_v
        }
    }

    # Сохраняем numpy массивы
    np.save('data/delta_k.npy', data_to_save['delta_k'])
    np.save('data/f_Maxwell.npy', data_to_save['f_M'])
    np.save('data/xi_grid.npy', data_to_save['xi_grid'])
    np.save('data/dxi.npy', data_to_save['dxi'])
    np.save('data/initial_norms.npy', data_to_save['initial_norms'])

    # Сохраняем скалярные параметры и векторы
    with open('data/parameters.json', 'w') as file:
        json.dump({
            'n': data_to_save['n'],
            'u': data_to_save['u'].tolist(),
            'T': data_to_save['T'],
            'u_star': data_to_save['u_star'].tolist(),
            'T_star': data_to_save['T_star'],
            'params': data_to_save['params']
        }, file, indent=4)

# Загружаем данные
def load_all_data():
    data = {'delta_k': np.load('data/delta_k.npy'), 'f_M': np.load('data/f_Maxwell.npy'),
            'xi_grid': np.load('data/xi_grid.npy'), 'dxi': np.load('data/dxi.npy'),
            'initial_norms': np.load('data/initial_norms.npy')}

    # Загружаем numpy массивы

    # Загружаем скалярные параметры
    with open('data/parameters.json', 'r') as file:
        params_data = json.load(file)
        data.update(params_data)
        data['u'] = np.array(data['u'])
        data['u_star'] = np.array(data['u_star'])

    return data

# Проверка целостности данных
def verify_data(original, loaded):
    # Проверка массивов
    checks = [
        ('delta_k', np.allclose(original['delta_k'], loaded['delta_k'], rtol=1e-6, atol=1e-8, equal_nan=True)),
        ('f_M', np.allclose(original['f_M'], loaded['f_M'])),
        ('xi_grid', np.allclose(original['xi_grid'], loaded['xi_grid'])),
        ('dxi', np.allclose(original['dxi'], loaded['dxi'])),
        ('initial_norms', np.allclose(original['initial_norms'], loaded['initial_norms'])),
        ('n', np.isclose(original['n'], loaded['n'])),
        ('u', np.allclose(original['u'], loaded['u'])),
        ('T', np.isclose(original['T'], loaded['T'])),
        ('u_star', np.allclose(original['u_star'], loaded['u_star'])),
        ('T_star', np.isclose(original['T_star'], loaded['T_star'])),
    ]

    # Проверка параметров
    param_checks = [
        (k, original['params'][k] == loaded['params'][k])
        for k in original['params']
    ]

    # Вывод результатов
    print("Результаты проверки:")
    for name, status in checks + param_checks:
        print(f"{name:15}: {'OK' if status else 'FAIL'}")

    return all(status for _, status in checks + param_checks)

In [176]:
# Сохраняем данные после выполнения основного кода
save_all_data()

# Загружаем данные
loaded_data = load_all_data()

# Создаём оригинальные данные для проверки
original_data = {
    'delta_k': delta_k,
    'f_M': f_M,
    'xi_grid': xi_grid,
    'dxi': dxi,
    'initial_norms': initial_norms,
    'n': n,
    'u': u,
    'T': T,
    'u_star': u_star,
    'T_star': T_star,
    'params': {
        'N': N,
        'xi_cut': xi_cut,
        'tau': tau,
        'T_tilde': T_tilde,
        'time_steps': time_steps,
        'N_0': N_0,
        'N_v': N_v
    }
}

# Проверяем целостность
if verify_data(original_data, loaded_data):
    print("\nВсе данные сохранены и загружены корректно!")
else:
    print("\nОбнаружены расхождения в данных!")

Результаты проверки:
delta_k        : OK
f_M            : OK
xi_grid        : OK
dxi            : OK
initial_norms  : OK
n              : OK
u              : OK
T              : OK
u_star         : OK
T_star         : OK
N              : OK
xi_cut         : OK
tau            : OK
T_tilde        : OK
time_steps     : OK
N_0            : OK
N_v            : OK

Все данные сохранены и загружены корректно!
