In [154]:
from sem_1 import *

In [155]:
xi_p, xi1_p = simulate_collisions(check_conservation=True, save_to_file=False)

Проверки сохранения:
Относительная скорость: 3.55e-15
Энергия: 4.26e-14
Импульс: 1.78e-15


In [156]:
xi_p

array([[-3.46660995,  3.56462741,  4.33038865],
       [-0.63544394,  6.4617911 , -0.19152047],
       [ 0.43096081, -1.45399377,  2.56597022],
       ...,
       [-4.59734967, -3.94887462,  0.48615945],
       [ 4.29738671, -0.32605958,  3.06045839],
       [-4.18932798, -5.89252281, -1.85822234]])

In [157]:
# семинар 2
from sem_2 import *

In [158]:
(xi_x, xi_y, xi_z), dxi = create_velocity_grid(20, 20, 20, 4.8)

In [159]:
a = create_random_params(20000)
normalize_params(a, 1.0, 4.8)

In [160]:
import sem_2
import importlib
importlib.reload(sem_2)
from sem_2 import *

a_snapped, snapped_idx = snap_collision_velocities(a, (xi_x, xi_y, xi_z), dxi)

In [161]:
a_snapped_filtered, snapped_idx_filtered = filter_collision_nodes(a_snapped, snapped_idx, 4.8)
print(np.shape(a_snapped_filtered))
print("Первая проверка по размеру пройдена")

(8, 5545)
Первая проверка по размеру пройдена


In [162]:
a_updated = compute_post_collision_velocities_sem_2(a_snapped_filtered, 1.0)

In [163]:
import sem_2
import importlib
importlib.reload(sem_2)
from sem_2 import *

lam1, lam2, mu1, mu2, r = find_interpolating_nodes_and_weights(a_updated, (xi_x, xi_y, xi_z), dxi, 4.8)

In [164]:
print(np.shape(lam1))
print("Вторая проверка по размеру пройдена")

(3, 3307)
Вторая проверка по размеру пройдена


In [165]:
print("проверка r:")
np.all((r >= 0) & (r <= 1))

проверка r:


True

In [166]:
print("Проверка закона сохранения импульса")
print("lam1 + mu1:")
print(lam1 + mu1)
print("lam2 + mu2:")
print(lam2 + mu2)
print("Видно, что все координаты либо совпадают, либо отличаются на +-1")

Проверка закона сохранения импульса
lam1 + mu1:
[[22 17 20 ... 26  4 20]
 [10 21 27 ... 27 19 21]
 [15 20 26 ... 24 22 12]]
lam2 + mu2:
[[21 18 21 ... 25  3 20]
 [ 9 22 28 ... 26 18 21]
 [14 21 27 ... 23 21 12]]
Видно, что все координаты либо совпадают, либо отличаются на +-1
